server:
  port: 8080

eureka:
  client: #\u5BA2\u6237\u7AEF\u6CE8\u518C\u8FDBeureka\u670D\u52A1\u5217\u8868\u5185
    service-url:
      #defaultZone: http://localhost:7001/eureka  #单机
      #集群
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: cloud_provider_8080
    prefer-ip-address: true     #\u8BBF\u95EE\u8DEF\u5F84\u53EF\u4EE5\u663E\u793AIP\u5730\u5740



info:
  app.name: micorserviceCloud
  company.name: www.wuqy.com
  build.artifactId: cloud_provider_8080
  build.version: 1.0-SNAPSHOT

spring:
  application:
    name: cloud-provider